source 'https://rubygems.org'
ruby '2.1.2'
gem 'rails', '4.0.2'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'figaro'
gem 'haml-rails'
gem 'simple_form'
gem 'thin'
gem 'httpclient'
gem 'twitter-bootswatch-rails', '~> 3.1.1'
gem 'therubyracer'
gem 'font-awesome-sass'
gem 'gemnasium-parser'
gem 'algoliasearch-rails'
gem 'hogan_assets'
gem 'nokogiri'
gem 'highlight', :require => 'simplabs/highlight'
gem 'simple_enum'
gem 'omniauth-github'
gem 'github-markup'
gem 'posix-spawn'
gem 'redcarpet'
gem 'RedCloth'
gem 'rdoc', '~> 3.6.1'
gem 'github_api'
gem 'parallel'
gem 'exception_notification'
gem 'hipchat'
gem 'classifier'
gem 'ruby-stemmer'
gem 'whenever'
gem 'd3_rails'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end
group :test do
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
end
group :production do
  gem 'mysql2'
end
